### ISSUE TITLE
Can not arm vehicle through Mavlink in monitor mode

### ISSUE THREAD

**Issue by mattgorski** [svpcom/wfb-ng#18]
Ive finally got everything tweaked and running great but for some reason vehicle did not respond to command Arm/Disarm when trying to arm the copter.  Any idea what causes this?  I can arm fine when connected IP direct via UDP but not in monitor mode.

Using PX4 and Pixhawk with SYS_COMPANION set it to 921600.

**Comment by svpcom** [comment]
wifibroadcast is unidirectional link. For arming vehicle you need bidirectional one like SiK radio

**Comment by mattgorski** [comment]
@svpcom Much appreciation on the response.  That makes sense.  I'll have to pickup a SiK radio for my setup.
