### ISSUE TITLE
[DOC] encryption.md improvements

### ISSUE THREAD

**Issue by maxlapshin** [svpcom/wfb-ng#272]
[Encryption.md](https://github.com/svpcom/wfb-ng/files/10454165/Encryption.md)

A bit more details about encryption process.

**Comment by maxlapshin** [comment]
[Home.md](https://github.com/svpcom/wfb-ng/files/10454770/Home.md)
[Setup-HOWTO.md](https://github.com/svpcom/wfb-ng/files/10454772/Setup-HOWTO.md)
[Mavlink-mode.md](https://github.com/svpcom/wfb-ng/files/10454774/Mavlink-mode.md)

Here are some other files. Not sure if it was a correct place for these edits.

**Comment by svpcom** [comment]
Applied. Thanks!
