### ISSUE TITLE
[DOC] docfix about udev rules

### ISSUE THREAD

**Issue by maxlapshin** [svpcom/wfb-ng#277]
Adding details about using udev rules

**Comment by maxlapshin** [comment]
[0001-Added-mention-about-udev.txt](https://github.com/svpcom/wfb-ng/files/10530300/0001-Added-mention-about-udev.txt)

patch file attached

**Comment by lida2003** [comment]
Well, that's what i have done lately.

[wfb-ng lock WiFi interface with udev](https://blog.csdn.net/lida2003/article/details/129389066)

**Comment by svpcom** [comment]
merged
