### ISSUE TITLE
Требует python3-all-dev

### ISSUE THREAD

**Issue by githubniko** [svpcom/wfb-ng#310]
Приветствую. При установке scripts/install_gs.sh возникла ошибка 
![image](https://github.com/svpcom/wfb-ng/assets/45603662/e78fb373-2f40-4b54-b5b4-6c553da70ba9)

Исправление
sudo apt install python3-all-dev

Ubuntu-rk3588

**Comment by svpcom** [comment]
Спасибо, поправил
