### ISSUE TITLE
[BUG]Unable to decrypt packet on wifi6 WNIC

### ISSUE THREAD

**Issue by zhouruixi** [svpcom/wfb-ng#365]
I run `wfb_rx` on an openwrt router[[Xiaomi Ax3600](https://openwrt.org/toh/xiaomi/ax3600)] to receive data. The router has both **wifi5**[Qualcomm Atheros **QCA9887**] and **wifi6**[Qualcomm Atheros **IPQ8074**] wireless network cards. I set them to the same channel and bandwidth. `wfb_rx` can decode data from the wifi5 wireless network card, but the data received from the wifi6 wireless network card cannot be decoded. **Thanks!**
<img width="440" alt="iw" src="https://github.com/user-attachments/assets/c400c024-b713-49c2-bd60-1bc85cf00284">
<img width="461" alt="iwinfo" src="https://github.com/user-attachments/assets/7b831521-e31c-4040-a6d9-b61cd66429c2">
<img width="1247" alt="wfb-rx" src="https://github.com/user-attachments/assets/92d44d86-e588-4dc0-9f65-25b5a00d875a">

**Comment by svpcom** [comment]
Try to capture with tcpdump (use `-w capture.dump`) from the both cards and upload it here. Maybe wifi6 card add some header

**Comment by zhouruixi** [comment]
> Try to capture with tcpdump (use `-w capture.dump`) from the both cards and upload it here. Maybe wifi6 card add some header

https://1drv.ms/f/s!AtB5-c6zgutCgY53ifYeQcWX5YASLg?e=DZUdZL

**Comment by svpcom** [comment]
I've found the root of this problem - in case of wifi6 it add 8 bytes (some garbage or additional data ?) to the end of captured packet. If I'll not found a good way to detect what it is then I'll just add command line flag to ignore last 8 bytes of the packet

**Comment by svpcom** [comment]
@zhouruixi Do you have another wifi6 adapter to check is this some wifi6 feature or this card (or driver) has implementation bug?

**Comment by zhouruixi** [comment]
> @zhouruixi Do you have another wifi6 adapter to check is this some wifi6 feature or this card (or driver) has implementation bug?

I use Ubuntu 24.04+Intel Ax211 for testing, and it works fine. I don't have other brands of wifi6 devices for more testing now. I have uploaded the data packets obtained on Ax211 to onedrive. Maybe it's the IPQ8074 driver problem or OpenWrt. I'm not a professional and don't have the ability to conduct in-depth analysis. I really want to use wfb_rx on the wifi6 openwrt router and hope you can give a solution. Thank you.

**Comment by svpcom** [comment]
@zhouruixi  Thanks for your dumps. They help me a lot to find root of this bug.

Quick solution for IPQ8074 is patch rx.cpp: 
```
@@ -242,7 +243,8 @@ void Receiver::loop_iter(void)
         /* discard the radiotap header part */
         pkt += iterator._max_length;
         pktlen -= iterator._max_length;
-
+        pktlen -= 8 ;
+        
         //fprintf(stderr, "CAPTURE: mcs: %u, bw: %u\n", mcs_index, bandwidth);
         if (pktlen > (int)sizeof(ieee80211_header))
         {
```
but I've not found a good way to distinguish bad and good cards during run time.
So for quick and dirty solution you can add condition into code if interface name equals to "bad card" then do `pktlen -= 8 ;`

**Comment by zhouruixi** [comment]
> @zhouruixi Thanks for your dumps. They help me a lot to find root of this bug.
> 
> Quick solution for IPQ8074 is patch rx.cpp:
> 
> ```diff
> @@ -242,7 +243,8 @@ void Receiver::loop_iter(void)
>          /* discard the radiotap header part */
>          pkt += iterator._max_length;
>          pktlen -= iterator._max_length;
> +        pktlen -= 8 ;
>        
>          //fprintf(stderr, "CAPTURE: mcs: %u, bw: %u\n", mcs_index, bandwidth);
>          if (pktlen > (int)sizeof(ieee80211_header))
>          {
> ```
> 
> but I've not found a good way to distinguish bad and good cards during run time. So for quick and dirty solution you can add condition into code if interface name equals to "bad card" then do `pktlen -= 8 ;`

1. It works on IPQ8074, but fails on wifi5. Does pktlen affect wfb aggregator?
2. We need more testing (wifi6 devices from other manufacturers, different drivers, and even wifi7 devices). If enough devices have pktlen issues, we can consider adding an additional command line flag

**Comment by svpcom** [comment]
1. Yes, it will fail on wifi5 because it doesn't feed extra bytes like ath11k on this router does. Yes it affects all wfb_rx modes. To work on wifi5 + wifi6 you need to add some "if" which will do `pktlen -= 8 ;` in case of wifi6 and do nothing in case of wifi5

**Comment by zhouruixi** [comment]
Working well with MediaTek based(MT7915E) wifi6 router. So this is just a non-universal problem caused by the ath11k driver. I will close this issue. Thanks again @svpcom

**Comment by svpcom** [comment]
@zhouruixi Please open issue on ath11k and/or openwrt about this bug. It is a real bug and it can affect other protocols

**Comment by zhouruixi** [comment]
Someone has found the same problem [here](https://github.com/openwrt/openwrt/issues/16183)

**Comment by legale** [comment]
> @zhouruixi Please open issue on ath11k and/or openwrt about this bug. It is a real bug and it can affect other protocols

I've tried to trigger ath11k before with no luck :)
https://lists.infradead.org/pipermail/ath11k/2022-December/003764.html

**Comment by svpcom** [comment]
@legale It seems a bug in ath11k firmware (it is fullmac driver compared to ath9k which is softmac), so only Qualcomm can fix it :-(

**Comment by Neustradamus** [comment]
Hope a real solution...

**Comment by Neustradamus** [comment]
This problem has been fixed?

**Comment by svpcom** [comment]
@Neustradamus This is a driver (or hw) bug. You can fix it adhoc like described above, but this will not be included into mainstream wfb-ng becase this breaks other (normal) cards
