### ISSUE TITLE
[REQUEST] Dynamic switching hooks/API for link quality

### ISSUE THREAD

**Issue by lida2003** [svpcom/wfb-ng#380]
I didn't find dynamic switching features for improving the link quality (packet loss).

This kind of dynamic tuning features should be useful for applications, such as FPV video feed. 

e.g. When flying an FPV

It will fly low altitude or fly behind obstacle(trees, walls etc) for a short period of time, or protentially will lose the packet. Then the application need to:

- increase the transmitting power
- enlarge the bandwidth
- decrease the bitrate
- etc

in order to get a stable feed without any glitches if possible.

And wfb-ng is a communication foundation of the FPV video trasmittion backbone tunnel. Hope there are hooks or interfaces for dynamic tunnings.

Then there are chances for link quality management. what do you think?

PS: I might be wrong, please correct me if I missed something.

**Comment by svpcom** [comment]
They already exists. See `wfb_tx_cmd`. Also you can connect to telemetry socket (like wfb-cli does) and get full link state (include rssi for every antenna, lost and recovered packets, etc). This API already used by openipc adaptive link https://www.youtube.com/watch?v=9WXtJEcyyeI

**Comment by svpcom** [comment]
https://github.com/sickgreg/OpenIPC-Adaptive-Link
